### ISSUE TITLE
[LogicalOptimizer] Schema

### ISSUE THREAD

**Issue by AveryQi115** [cmu-db/optd-original#56]
# TODO
- [x] add names and is_nullable to schema
    - https://github.com/cmu-db/optd/pull/61
- [x] make schema types align with datafusion::arrow::Schema type (one to one mapping)
    - https://github.com/cmu-db/optd/pull/57
- [x] adjust schema derivation in existing rules
    - [ ] future work: accurate nullable derivation for aggregations
