### ISSUE TITLE
Tracking: make sure optd does not crash for TPC-H queries

### ISSUE THREAD

**Issue by Gun9niR** [cmu-db/optd-original#68]
- [x] Q1 #78 
  - 🚧 Not working in perftest: `Error: ArrowError(NotYetImplemented("Unsupported Interval Expression with value \"115 day (3) seconds\""))`
- [x] Q2 #80 
- [x] Q3 #86 
- [ ] Q4
  - optd panics with `cannot find best binding for group` (Not supporting left semi join)
- [x] Q5 #69 
- [x] Q6 #69 
  - 🚧 Working in optd but not in DataFusion: `Error: Arrow error: Invalid argument error: Invalid comparison operation: Decimal128(15, 2) >= Decimal128(20, 0)`
- [x] Q7 #72 
- [x] Q8 https://github.com/cmu-db/optd/pull/64
- [x] Q9 #72 
- [x] Q10 #78 
- [x] Q11
  - Non-equal join filer
- [x] Q12 #77 
- [x] Q13
  - DF `Join` `filter` says `Filters applied during join (non-equi conditions)`, but there can actually be equal comparisons!
  - Non-equal join filter
- [x] Q14 #78 
- [x] Q15 #86 
  - 🚧 Not working in perftest: `unsupported plan node: CreateView: Bare { table: "revenue0" }`
- [ ] Q16
  - optd panics with `cannot find best binding for group`(Not supporting left anti join)
- [x] Q17 #86 
- [ ] Q18
  - optd panics with `cannot find best binding for group` (Not supporting left semi join)
- [x] Q19 #77 
- [ ] Q20
  - optd panics with `cannot find best binding for group` (Not supporting left semi join)
- [ ] Q21
  - optd panics with `cannot find best binding for group` (Not supporting left semi and left anti join)
- [ ] Q22
  - optd panics with `cannot find best binding for group`(Not supporting left anti join)
### Missing features
- [x] Subquery: Q2, Q3, Q4, Q11, Q16, Q17, Q20, Q21, Q22
  - Correlated subquery is not supported in DF physical optimizer. DF's logical optimizer eliminates `OuterReferenceColumn` by moving the column to the outer query. Since we do not know how to access columns of the outer query, I think we should enable DF's logical optimizer when dealing with subqueries.
  - ~With DF's logical optimizer enabled, we get `Error during planning: table 'datafusion.public.xxxx' not found` error.~ When using `explain_with_logical` in the planner test, make sure to execute the DDLs with `execute_with_logical`!
- [x] `InListExpr`: Q12, Q16, Q19 #77 
- [x] `IntervalMonthDayNano`: Q1, Q10, Q14(#78)
- [x] Multiple (non-equal) predicates for one join: Q11, Q13, Q22
- [x] `ColumnRefPropertyBulder`
  - [x] `LogOp`: Q16
- [ ] Left anti and left semi join: Q4, Q16, Q18, Q20, Q21, Q22

**Comment by jurplel** [comment]
We should test more TPC-H queries and make a list of what features we're missing.

**Comment by AveryQi115** [comment]
It seems q1 is failed for card test:

Error: Arrow error: Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"

Caused by:
    Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"

**Comment by Gun9niR** [comment]
> It seems q1 is failed for card test:
> 
> Error: Arrow error: Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"
> 
> Caused by: Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"

That seems to be coming from DF (parser prob), not optd 🥲

**Comment by Gun9niR** [comment]
> It seems q1 is failed for card test:
> 
> Error: Arrow error: Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"
> 
> Caused by: Not yet implemented: Unsupported Interval Expression with value "115 day (3) seconds"

The error is thrown from `SessionState::statement_to_plan`, which means it's DF's problem, not optd's. We can modify the tpch template so it generates something DF supports.
